name: Notify

on:
  workflow_run:
    workflows: ["main"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Deployment Notification to Teams
        uses: gabriel-vasile/ms-teams-notification-action@v1
        with:
          webhook-url: ${{ secrets.M_WEBHOOK }}
          message: 'Build is successful!'
